language: objective-c
osx_image: xcode9.2

script:
 - xcodebuild build -project ETBinding.xcodeproj -scheme ETBinding-iOS -configuration "Release" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 - xcodebuild test -project ETBinding.xcodeproj -scheme ETBinding-iOS -configuration "Debug" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X'
